### ISSUE TITLE
ssl.CertificateError aka Can't use bucket names with dots

### ISSUE THREAD

**Issue by benbuckman** [richarvey/s3redirect#1]
This library seems to be affected by this bug: https://github.com/boto/boto/issues/2836

```
ssl.CertificateError: hostname 'my.bucket.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com'
```

I'm not very familiar with Python or Boto, and haven't yet figured out how to work around this.
Any advice would be greatly appreciated.

**Comment by richarvey** [comment]
rewrite coming
